### PR TITLE
Upgrading the babel presets to avoid warning.

### PR DESCRIPTION
**Pull request by jrgleason**
I was getting some warnings and I am trying to solve that

### CODE REVIEW

**Comment by jrgleason** [comment]
I think this is ready for a squash and merge. Once that is done I will finish working on the other one.

**Comment by Akryum** [comment]
Thanks for your PR! :smile:

**Comment by jrgleason** [comment]
Better?

**Comment by jrgleason** [comment]
P.S. should we add that to the .gitignore then?

**Pull request merged**
